### ISSUE TITLE
Google 翻訳でコードブロックの中身が壊れる

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#23]
当たり前といえば当たり前なのだが、チュートリアルを Gooogle 翻訳で英語にして読んでいる場合にコードブロックをそのままコピペして実行しようとすると動かないことがある。

全て英語でちゃんと書かれたページを用意できればそれで良いのだけど、何か他に対策がないか。

 - 翻訳対象外とマークする方法がないか
  - lang=en とか付けておけばスルーしたりしないか？

**Comment by dynamis** [comment]
class="notranslate" を付ければ良いらしい

https://webmasters.googleblog.com/2008/10/helping-you-break-language-barrier.html

ただコードブロックを書く度にこれを付けるのって超面倒で絶対作業抜けが発生する。
サイトのビルド (jekyll や netlify) 側で何とか出来ないか検討したいところ。

**Comment by sizuhiko** [comment]
現時点のGitHub PagesはJekyll3系なので、以下のように `_config.yml` に記述すると `class` を追加できると思います。

```yml
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'notranslate'
```
