### ISSUE TITLE
GitHub Flavored Markdown にする

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#24]
現状 Netlify でビルドしているものは GitHub Flavored Markdown https://github.github.com/gfm/ になっていないのは GitHub Pages が勝手に入れているデフォルト設定が Netlify のビルド時には含まれないからと思われる。

https://help.github.com/articles/configuring-jekyll/

```
 github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-primer
 gfm_quirks: paragraph_end

 lsi: false
 safe: true
 source: [your repo's top level directory]
 incremental: false
 highlighter: rouge
 gist:
   noscript: false
 kramdown:
   math_engine: mathjax
   syntax_highlighter: rouge
```
